Update scraper.yaml

diff --git a/.github/workflows/scraper.yaml b/.github/workflows/scraper.yaml
--- a/.github/workflows/scraper.yaml
+++ b/.github/workflows/scraper.yaml
@@ -97,25 +97,26 @@ jobs:
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-      
+
           git add output/*.csv || true
-      
-          if git diff --staged --quiet; then
+
+          if git diff --cached --quiet; then
             echo "No changes"
             exit 0
           fi
-      
+
           git commit -m "Update CSV"
-      
+
           for i in 1 2 3
           do
-            git pull --rebase origin main && \
-            git push origin main && break
-      
-            echo "Retry $i"
+            git push origin HEAD:main && break
+
+            echo "Push failed. Retry $i"
+
             sleep 10
+
+            git pull --ff-only origin main || true
+            git rebase origin/main || true
           done
-
-
 
           
